/**
 * Minimal country list for server-side score verification.
 * Duplicates only {code, name, aliases} from src/data/countries.ts —
 * api/ cannot import from src/ (server vs. client bundle boundary).
 */

export type ServerCountry = {
  code: string;
  name: string;
  aliases?: string[];
};

export const COUNTRIES: ServerCountry[] = [
  // ── Africa ────────────────────────────────────────────────────────────────
  { code: 'ng', name: 'Nigeria' },
  { code: 'gh', name: 'Ghana' },
  { code: 'ke', name: 'Kenya' },
  { code: 'za', name: 'South Africa' },
  { code: 'eg', name: 'Egypt' },
  { code: 'ma', name: 'Morocco' },
  { code: 'et', name: 'Ethiopia' },
  { code: 'sn', name: 'Senegal' },
  { code: 'cm', name: 'Cameroon' },
  { code: 'tz', name: 'Tanzania' },
  { code: 'ug', name: 'Uganda' },
  { code: 'ci', name: 'Ivory Coast', aliases: ["Côte d'Ivoire", "Cote d'Ivoire", 'Cote d Ivoire'] },
  { code: 'ao', name: 'Angola' },
  { code: 'mz', name: 'Mozambique', aliases: ['Mozanbique', 'Mozambiq'] },
  { code: 'zm', name: 'Zambia' },
  { code: 'zw', name: 'Zimbabwe' },
  { code: 'rw', name: 'Rwanda' },
  { code: 'sd', name: 'Sudan' },
  { code: 'dz', name: 'Algeria' },
  { code: 'tn', name: 'Tunisia' },
  { code: 'lr', name: 'Liberia' },
  { code: 'sl', name: 'Sierra Leone' },
  { code: 'gm', name: 'Gambia' },
  { code: 'bj', name: 'Benin' },
  { code: 'tg', name: 'Togo' },
  { code: 'bf', name: 'Burkina Faso' },
  { code: 'ml', name: 'Mali' },
  { code: 'ne', name: 'Niger' },
  { code: 'td', name: 'Chad' },
  { code: 'cd', name: 'DR Congo', aliases: ['DRC', 'Democratic Republic of the Congo', 'Congo DR', 'Congo DRC'] },
  { code: 'cg', name: 'Republic of the Congo' },
  { code: 'ga', name: 'Gabon' },
  { code: 'gq', name: 'Equatorial Guinea' },
  { code: 'bi', name: 'Burundi' },
  { code: 'km', name: 'Comoros' },
  { code: 'sc', name: 'Seychelles', aliases: ['Sychelles'] },
  { code: 'mu', name: 'Mauritius', aliases: ['Mauritus'] },
  { code: 'mg', name: 'Madagascar' },
  { code: 'cv', name: 'Cabo Verde' },
  { code: 'st', name: 'Sao Tome and Principe' },
  { code: 'er', name: 'Eritrea' },
  { code: 'dj', name: 'Djibouti', aliases: ['Djibuti', 'Jibouti'] },
  { code: 'so', name: 'Somalia' },
  { code: 'ly', name: 'Libya' },
  { code: 'mr', name: 'Mauritania' },
  { code: 'gw', name: 'Guinea-Bissau' },
  { code: 'gn', name: 'Guinea' },
  { code: 'mw', name: 'Malawi' },
  { code: 'sz', name: 'Eswatini', aliases: ['Swaziland'] },
  { code: 'ls', name: 'Lesotho' },
  { code: 'bw', name: 'Botswana' },
  { code: 'na', name: 'Namibia' },

  // ── Europe ────────────────────────────────────────────────────────────────
  { code: 'fr', name: 'France' },
  { code: 'de', name: 'Germany' },
  { code: 'gb', name: 'United Kingdom' },
  { code: 'it', name: 'Italy' },
  { code: 'es', name: 'Spain' },
  { code: 'pt', name: 'Portugal' },
  { code: 'nl', name: 'Netherlands' },
  { code: 'be', name: 'Belgium' },
  { code: 'se', name: 'Sweden' },
  { code: 'no', name: 'Norway' },
  { code: 'pl', name: 'Poland' },
  { code: 'gr', name: 'Greece' },
  { code: 'ch', name: 'Switzerland' },
  { code: 'at', name: 'Austria' },
  { code: 'dk', name: 'Denmark' },
  { code: 'fi', name: 'Finland' },
  { code: 'ie', name: 'Ireland' },
  { code: 'cz', name: 'Czech Republic' },
  { code: 'sk', name: 'Slovakia' },
  { code: 'hu', name: 'Hungary' },
  { code: 'ro', name: 'Romania' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'hr', name: 'Croatia' },
  { code: 'si', name: 'Slovenia' },
  { code: 'rs', name: 'Serbia' },
  { code: 'ba', name: 'Bosnia and Herzegovina' },
  { code: 'me', name: 'Montenegro' },
  { code: 'mk', name: 'North Macedonia' },
  { code: 'al', name: 'Albania' },
  { code: 'cy', name: 'Cyprus' },
  { code: 'lt', name: 'Lithuania' },
  { code: 'lv', name: 'Latvia' },
  { code: 'ee', name: 'Estonia' },
  { code: 'by', name: 'Belarus' },
  { code: 'md', name: 'Moldova' },
  { code: 'ua', name: 'Ukraine' },
  { code: 'ru', name: 'Russia' },
  { code: 'is', name: 'Iceland' },
  { code: 'lu', name: 'Luxembourg' },
  { code: 'mt', name: 'Malta' },
  { code: 'sm', name: 'San Marino' },
  { code: 'va', name: 'Vatican City' },
  { code: 'li', name: 'Liechtenstein' },
  { code: 'mc', name: 'Monaco' },
  { code: 'ad', name: 'Andorra' },

  // ── Americas ──────────────────────────────────────────────────────────────
  { code: 'us', name: 'United States' },
  { code: 'ca', name: 'Canada' },
  { code: 'br', name: 'Brazil' },
  { code: 'ar', name: 'Argentina' },
  { code: 'mx', name: 'Mexico' },
  { code: 'co', name: 'Colombia', aliases: ['Columbia'] },
  { code: 'cl', name: 'Chile' },
  { code: 'pe', name: 'Peru' },
  { code: 've', name: 'Venezuela' },
  { code: 'ec', name: 'Ecuador' },
  { code: 'bo', name: 'Bolivia' },
  { code: 'py', name: 'Paraguay' },
  { code: 'uy', name: 'Uruguay' },
  { code: 'gy', name: 'Guyana' },
  { code: 'sr', name: 'Suriname' },
  { code: 'bb', name: 'Barbados' },
  { code: 'jm', name: 'Jamaica' },
  { code: 'tt', name: 'Trinidad and Tobago' },
  { code: 'ht', name: 'Haiti' },
  { code: 'do', name: 'Dominican Republic' },
  { code: 'cu', name: 'Cuba' },
  { code: 'cr', name: 'Costa Rica' },
  { code: 'pa', name: 'Panama' },
  { code: 'ni', name: 'Nicaragua' },
  { code: 'hn', name: 'Honduras' },
  { code: 'gt', name: 'Guatemala' },
  { code: 'bz', name: 'Belize' },
  { code: 'sv', name: 'El Salvador' },

  // ── Asia ──────────────────────────────────────────────────────────────────
  { code: 'jp', name: 'Japan' },
  { code: 'cn', name: 'China' },
  { code: 'in', name: 'India' },
  { code: 'kr', name: 'South Korea' },
  { code: 'id', name: 'Indonesia' },
  { code: 'th', name: 'Thailand' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'ph', name: 'Philippines', aliases: ['Phillipines', 'Phillippines', 'Filipines'] },
  { code: 'sg', name: 'Singapore' },
  { code: 'my', name: 'Malaysia' },
  { code: 'bd', name: 'Bangladesh' },
  { code: 'pk', name: 'Pakistan' },
  { code: 'lk', name: 'Sri Lanka' },
  { code: 'np', name: 'Nepal' },
  { code: 'bt', name: 'Bhutan' },
  { code: 'mm', name: 'Myanmar', aliases: ['Burma'] },
  { code: 'kh', name: 'Cambodia' },
  { code: 'la', name: 'Laos' },
  { code: 'mn', name: 'Mongolia' },
  { code: 'kz', name: 'Kazakhstan', aliases: ['Kazakstan', 'Khazakstan'] },
  { code: 'uz', name: 'Uzbekistan' },
  { code: 'tm', name: 'Turkmenistan' },
  { code: 'tj', name: 'Tajikistan' },
  { code: 'kg', name: 'Kyrgyzstan', aliases: ['Kyrgystan', 'Kirgizstan'] },
  { code: 'af', name: 'Afghanistan' },
  { code: 'ir', name: 'Iran' },
  { code: 'iq', name: 'Iraq' },
  { code: 'sa', name: 'Saudi Arabia' },
  { code: 'ae', name: 'UAE' },
  { code: 'tr', name: 'Turkey' },
  { code: 'il', name: 'Israel', aliases: ['Isreal', 'Isarel', 'Isarael'] },
  { code: 'jo', name: 'Jordan' },
  { code: 'lb', name: 'Lebanon' },
  { code: 'sy', name: 'Syria' },
  { code: 'ye', name: 'Yemen' },
  { code: 'om', name: 'Oman' },
  { code: 'kw', name: 'Kuwait' },
  { code: 'qa', name: 'Qatar' },
  { code: 'bh', name: 'Bahrain' },
  { code: 'am', name: 'Armenia' },
  { code: 'az', name: 'Azerbaijan', aliases: ['Azerbaijian'] },
  { code: 'ge', name: 'Georgia' },

  // ── Oceania ───────────────────────────────────────────────────────────────
  { code: 'au', name: 'Australia' },
  { code: 'nz', name: 'New Zealand' },
  { code: 'fj', name: 'Fiji' },
  { code: 'pg', name: 'Papua New Guinea' },
  { code: 'sb', name: 'Solomon Islands' },
  { code: 'vu', name: 'Vanuatu' },
  { code: 'ws', name: 'Samoa' },
  { code: 'to', name: 'Tonga' },
  { code: 'ki', name: 'Kiribati' },
  { code: 'tv', name: 'Tuvalu' },
  { code: 'nr', name: 'Nauru' },
  { code: 'pw', name: 'Palau' },
  { code: 'fm', name: 'Micronesia' },
  { code: 'mh', name: 'Marshall Islands' },
];

// Build a fast lookup map: code → country
export const COUNTRY_MAP = new Map<string, ServerCountry>(
  COUNTRIES.map(c => [c.code, c]),
);
